import type { Metadata } from "next";
import { Inter, Anton } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import ScrollButton from "@/components/ui/ScrollButton";
import LenisScroll from "@/components/ui/LenisScroll";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
const anton = Anton({
  variable: "--font-anton",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${anton.variable}`}>
      <body className="font-sans">
        <Header />
        <div style={{ minHeight: '100vh' }}>
          <LenisScroll />
          {children}
          <ScrollButton />
        </div>
        <Footer />
      </body>
    </html>
  );
}